### ISSUE TITLE
Activated tramlines when seed drill is raised

### ISSUE THREAD

**Issue by AchhammerSebastian** [stijnwop/proSeed#15] opened 2020-07-10 18:59 UTC
Tramlines are also drawn when the seed drill is raised. can you deactivate this?

**Comment by Snickers125** [comment] 2020-07-18 19:22
downgrade to an older version (like ModHub) 
Duplicate of #10

**Comment by JimmyBeam1990** [comment] 2020-07-28 13:19
The current Mofhub version has the same error, can you somehow deactivate it? when driving with GPS and in car mode, the seed rail is already drawing lanes in the turning curtain.

**Comment by derDeBen** [comment] 2020-07-28 23:10
thats not right current Version from Modhub doesn`t had these issue.
Tried it some minutes ago.

**Closed** 2021-01-02 15:06 UTC
Labels: bug, fixed
